### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by anton-petrov** [xmapst/kubefilebrowser#12]
Hello and thank you for your amazing project! 
Is it possible to add english language support? As far as I understand it is necessary to edit [translation file ](https://github.com/xmapst/kubefilebrowser/blob/main/webui/src/lang/en.js)?

**Comment by xmapst** [comment]
> Hello and thank you for your amazing project! Is it possible to add english language support? As far as I understand it is necessary to edit [translation file ](https://github.com/xmapst/kubefilebrowser/blob/main/webui/src/lang/en.js)?

sure

**Comment by mtahle** [comment]
Hello @xmapst 

I want to contribute by translating the application. Can you guide me to the proper steps?
