### ISSUE TITLE
tar: kftools: Cannot open: Read-only file system

### ISSUE THREAD

**Issue by ssongliu** [xmapst/kubefilebrowser#2]
你好，我在打开浏览器的时候，会报一个 tar: can't remove old file kftools: Read-only file system 的错误，请问这是什么问题呢？
![image](https://user-images.githubusercontent.com/73214554/154944847-6bf87374-b97f-4d35-b5c5-9a0afc5e19b6.png)

**Comment by xmapst** [comment]
> 你好，我在打开浏览器的时候，会报一个 tar: can't remove old file kftools: Read-only file system 的错误，请问这是什么问题呢？ ![image](https://user-images.githubusercontent.com/73214554/154944847-6bf87374-b97f-4d35-b5c5-9a0afc5e19b6.png)

检查一下该容器的文件系统是否为只读

**Comment by ssongliu** [comment]
> > 你好，我在打开浏览器的时候，会报一个 tar: can't remove old file kftools: Read-only file system 的错误，请问这是什么问题呢？ ![image](https://user-images.githubusercontent.com/73214554/154944847-6bf87374-b97f-4d35-b5c5-9a0afc5e19b6.png)
> 
> 检查一下该容器的文件系统是否为只读

感谢回复，确实是我容器 file system 权限是 readonly 的问题
不过我又遇到了一个小问题，安装 kftools 成功后，执行 /kftools ls 命令失败，直接进入容器手动执行也是失败，操作及错误信息为： 
1.  手动执行
![image](https://user-images.githubusercontent.com/73214554/155057745-298c6512-f493-41ca-aefa-1f5582a2a730.png)
2.  kubefilebrowser
![image](https://user-images.githubusercontent.com/73214554/155057894-68be7916-1aaf-47a6-9d3a-ec6a12a7f412.png)
生成的二进制文件 kftools_linux_amd64，本地执行 ls 命令是没问题的

**Comment by xmapst** [comment]
> 

已知问题, 一会发布新版

**Comment by ssongliu** [comment]
> 

感谢感谢！

**Comment by xmapst** [comment]
> > 
> 
> 感谢感谢！

已发布, 从release下载最新的运行试试

**Comment by ssongliu** [comment]
> > > 
> > 
> > 
> > 感谢感谢！
> 
> 已发布, 从release下载最新的运行试试

![image](https://user-images.githubusercontent.com/73214554/155081479-fa1eb809-d722-4e78-b6ee-63a90c3df7e7.png)

改成 pod.Spec.NodeName 后还是和之前一样的问题...  方便加个联系方式吗？

**Comment by xmapst** [comment]
> > > > 
> > > 
> > > 
> > > 感谢感谢！
> > 
> > 
> > 已发布, 从release下载最新的运行试试
> 
> ![image](https://user-images.githubusercontent.com/73214554/155081479-fa1eb809-d722-4e78-b6ee-63a90c3df7e7.png)
> 
> 改成 pod.Spec.NodeName 后还是和之前一样的问题... 方便加个联系方式吗？

xmapst@gmail.com

**Comment by xmapst** [comment]
> > > > 
> > > 
> > > 
> > > 感谢感谢！
> > 
> > 
> > 已发布, 从release下载最新的运行试试
> 
> ![image](https://user-images.githubusercontent.com/73214554/155081479-fa1eb809-d722-4e78-b6ee-63a90c3df7e7.png)
> 
> 改成 pod.Spec.NodeName 后还是和之前一样的问题... 方便加个联系方式吗？

麻烦提供一下你k8s环境的操作系统类型及cpu架构

**Comment by ssongliu** [comment]
> 

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/73214554/155146916-fc3cbedc-103c-4d05-84b7-9c95d0f1b832.png">

**Comment by xmapst** [comment]
> > 
> 
> <img alt="image" width="1313" src="https://user-images.githubusercontent.com/73214554/155146916-fc3cbedc-103c-4d05-84b7-9c95d0f1b832.png">

![image](https://user-images.githubusercontent.com/36829716/155271534-01dcffec-cadd-4f78-81e0-9bb7a8589a6e.png)
测试没问题的

**Comment by ssongliu** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="1313" src="https://user-images.githubusercontent.com/73214554/155146916-fc3cbedc-103c-4d05-84b7-9c95d0f1b832.png">
> 
> ![image](https://user-images.githubusercontent.com/36829716/155271534-01dcffec-cadd-4f78-81e0-9bb7a8589a6e.png) 测试没问题的

好的，感谢回复！我自己再研究研究

**Comment by xmapst** [comment]
> > > > 
> > > 
> > > 
> > > <img alt="image" width="1313" src="https://user-images.githubusercontent.com/73214554/155146916-fc3cbedc-103c-4d05-84b7-9c95d0f1b832.png">
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/36829716/155271534-01dcffec-cadd-4f78-81e0-9bb7a8589a6e.png) 测试没问题的
> 
> 好的，感谢回复！我自己再研究研究

有问题可以加我微信, xmapst
