### ISSUE TITLE
Dockerfile: swag init error

### ISSUE THREAD

**Issue by fangfenghuang** [xmapst/kubefilebrowser#3]
```
[root@tztest kubefilebrowser]# docker build --network host --rm --build-arg APP_ROOT=/go/src/kubefilebrowser -t kubefilebrowser:latest -f Dockerfile .
...
2022/04/22 07:40:14 Generate general API Info, search dir:./
2022/04/22 07:40:14 Generate swagger docs....
2022/04/22 07:40:16 cannot parse source files /go/src/kubefilebrowser/main.go: open /go/src/kubefilebrowser/main.go: no such file or directory
```

```
> Dockerfile
# build code
RUN go get -u github.com/swaggo/swag/cmd/swag \
  && swag init \
```
is that necessary  to "swag init"  here?

**Comment by xmapst** [comment]
> ```
> [root@tztest kubefilebrowser]# docker build --network host --rm --build-arg APP_ROOT=/go/src/kubefilebrowser -t kubefilebrowser:latest -f Dockerfile .
> ...
> 2022/04/22 07:40:14 Generate general API Info, search dir:./
> 2022/04/22 07:40:14 Generate swagger docs....
> 2022/04/22 07:40:16 cannot parse source files /go/src/kubefilebrowser/main.go: open /go/src/kubefilebrowser/main.go: no such file or directory
> ```
> 
> ```
> > Dockerfile
> # build code
> RUN go get -u github.com/swaggo/swag/cmd/swag \
>   && swag init \
> ```
> 
> is that necessary to "swag init" here?

use `swag init -g cmd/server/main.go`

**Comment by fangfenghuang** [comment]
got it
